//const msg = "Hola Mundo" 

//console.log(msg);


//const numeros = [1,2,3,4,5];

//const numeros2 = [0,... numeros,6,7,8];

//console.log(numeros2)


/*function range(start, end,step) {


   
   
       if(start < end && step==null)
       {
        for (let i=start; i<=end;i++)
        {
           
         numbers.push([i]) 
                 
        }

       }
       else if(step>0)
       {

            
        for (let i=start; i<=end;i++)
        {
        
         if(start<=end)

         {
            numbers.push(start)  

            start = start + step;

         }   
             
                        
        }
        }
 
       
       
              
    
     
       
    return numbers;
     
  }


  //console.log( range(1, 5) );
  //console.log( range(1, 10, 2) ); // [1, 3, 5, 7, 9]
  console.log( range(5, 2, -1) ); // [5, 4, 3, 2]*/

  